const axios = require("axios");
const { GoogleGenAI } = require("@google/genai");

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});



class AIController {
  static async suggestRecipe(req, res, next) {
    try {
      const { ingredients } = req.body;

      if (
        !ingredients ||
        !Array.isArray(ingredients) ||
        ingredients.length === 0
      ) {
        throw {
          name: "BadRequestING"
        };
      }

      // Bersihkan input
      const cleanIngredients = ingredients
        .map((item) => item.trim().toLowerCase())
        .filter((item) => item.length > 0);

      if (cleanIngredients.length === 0) {
        throw {
          name: "BadRequestING",
        };
      }

      // console.log("Ingredients:", cleanIngredients);

      const response = await axios.get(
        "https://api.spoonacular.com/recipes/findByIngredients",
        {
          params: {
            apiKey: process.env.SPOONACULAR_API_KEY,
            ingredients: cleanIngredients.join(","),
            number: 5,
            ranking: 1,
            ignorePantry: true,
          },
        },
      );

      const recipes = response.data;

      // console.log("Spoonacular recipes:", recipes);

      const suitableRecipes = recipes.filter((recipe) => {
        return (
          recipe.usedIngredientCount >= Math.ceil(cleanIngredients.length * 0.7)
        );
      });

      if (suitableRecipes.length > 0) {
        return res.status(200).json({
          source: "spoonacular",
          message: "Recipe found from Spoonacular",
          data: suitableRecipes.slice(0, 5),
        });
      }

      const prompt = `
You are a cooking assistant for a recipe application.

The user has these ingredients:

${cleanIngredients.map((item) => `- ${item}`).join("\n")}

Create ONE practical recipe using these ingredients.

Rules:
- Use the user's ingredients as the main ingredients.
- Use as many of the user's ingredients as possible.
- You may add common basic ingredients such as salt, pepper, cooking oil, and water.
- Do not use rare or expensive ingredients unless necessary.
- Make sure the recipe is actually possible to cook.
- Give clear cooking instructions.
- Return only the requested JSON structure.
`;

      const result = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,

        config: {
          responseMimeType: "application/json",

          responseSchema: {
            type: "object",

            properties: {
              title: {
                type: "string",
              },

              readyInMinutes: {
                type: "integer",
              },

              servings: {
                type: "integer",
              },

              ingredients: {
                type: "array",

                items: {
                  type: "object",

                  properties: {
                    name: {
                      type: "string",
                    },

                    amount: {
                      type: "number",
                    },

                    unit: {
                      type: "string",
                    },
                  },

                  required: ["name", "amount", "unit"],
                },
              },

              instructions: {
                type: "array",

                items: {
                  type: "string",
                },
              },
            },

            required: [
              "title",
              "readyInMinutes",
              "servings",
              "ingredients",
              "instructions",
            ],
          },
        },
      });


      const recipe = JSON.parse(result.text);



      return res.status(200).json({
        source: "gemini",
        message: "Recipe generated by AI",
        data: recipe,
      });
    } catch (error) {
      console.log(error);
      next(error);
    }
  }

  static async suggestRecipeFromPhoto(req, res, next) {
    try {
      if (!req.file) {
        throw { name: "BadRequestpho"};
      }

      const base64Image = req.file.buffer.toString("base64");
      const mimeType = req.file.mimetype;

      const visionResult = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: [
          {
            role: "user",
            parts: [
              { inlineData: { mimeType, data: base64Image } },
              {
                text: "Identify all edible food ingredients visible in this image. Only list real ingredient names, no packaging/utensils.",
              },
            ],
          },
        ],
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: "object",
            properties: {
              ingredients: { type: "array", items: { type: "string" } },
            },
            required: ["ingredients"],
          },
        },
      });

      const detected = JSON.parse(visionResult.text);

      if (!detected.ingredients || detected.ingredients.length === 0) {
        throw {
          name: "noIngridient"
        };
      }


      req.body.ingredients = detected.ingredients;

      return AIController.suggestRecipe(req, res, next);
    } catch (error) {
      console.log(error);
      next(error);
    }
  }


}

module.exports = AIController;
